//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.zamanimyok.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flowRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public flowRequest()
        {
            this.flowRequestDetails = new HashSet<flowRequestDetail>();
            this.flowReservations = new HashSet<flowReservation>();
        }
    
        public int PK { get; set; }
        public Nullable<int> InstanceFK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> AffiliateFK { get; set; }
        public Nullable<int> ServantFK { get; set; }
        public Nullable<int> ServiceFK { get; set; }
        public Nullable<int> StatusFK { get; set; }
        public string Extras { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime RemovalDate { get; set; }
        public string RemovedBy { get; set; }
        public bool Present { get; set; }
    
        public virtual affSelf affSelf { get; set; }
        public virtual affService affService { get; set; }
        public virtual authInstance authInstance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flowRequestDetail> flowRequestDetails { get; set; }
        public virtual serSelf serSelf { get; set; }
        public virtual flowRequestState flowRequestState { get; set; }
        public virtual userSelf userSelf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flowReservation> flowReservations { get; set; }
    }
}
