//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.zamanimyok.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public logLocation()
        {
            this.logHttps = new HashSet<logHttp>();
        }
    
        public int PK { get; set; }
        public Nullable<int> CountryFK { get; set; }
        public Nullable<int> RegionFK { get; set; }
        public Nullable<int> CityFK { get; set; }
        public string IP { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Extras { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime RemovalDate { get; set; }
        public string RemovedBy { get; set; }
        public bool Present { get; set; }
    
        public virtual logCity logCity { get; set; }
        public virtual logCountry logCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logHttp> logHttps { get; set; }
        public virtual logRegion logRegion { get; set; }
    }
}
