//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.zamanimyok.com.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_Dev : DbContext
    {
        public Entities_Dev()
            : base("name=Entities_Dev")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<affCity> affCities { get; set; }
        public virtual DbSet<affDetail> affDetails { get; set; }
        public virtual DbSet<affDistrict> affDistricts { get; set; }
        public virtual DbSet<affFranchise> affFranchises { get; set; }
        public virtual DbSet<affKey> affKeys { get; set; }
        public virtual DbSet<affLocation> affLocations { get; set; }
        public virtual DbSet<affMember> affMembers { get; set; }
        public virtual DbSet<affMemberDetail> affMemberDetails { get; set; }
        public virtual DbSet<affMemberKey> affMemberKeys { get; set; }
        public virtual DbSet<affPricing> affPricings { get; set; }
        public virtual DbSet<affPricingDetail> affPricingDetails { get; set; }
        public virtual DbSet<affPricingKey> affPricingKeys { get; set; }
        public virtual DbSet<affSelf> affSelves { get; set; }
        public virtual DbSet<affService> affServices { get; set; }
        public virtual DbSet<authCredential> authCredentials { get; set; }
        public virtual DbSet<authCredentialDetail> authCredentialDetails { get; set; }
        public virtual DbSet<authCredentialKey> authCredentialKeys { get; set; }
        public virtual DbSet<authDevice> authDevices { get; set; }
        public virtual DbSet<authInstance> authInstances { get; set; }
        public virtual DbSet<authInstanceState> authInstanceStates { get; set; }
        public virtual DbSet<authLogin> authLogins { get; set; }
        public virtual DbSet<authLoginDetail> authLoginDetails { get; set; }
        public virtual DbSet<authLoginKey> authLoginKeys { get; set; }
        public virtual DbSet<authLoginState> authLoginStates { get; set; }
        public virtual DbSet<authMember> authMembers { get; set; }
        public virtual DbSet<authMemberDevice> authMemberDevices { get; set; }
        public virtual DbSet<authModel> authModels { get; set; }
        public virtual DbSet<authO> authOS { get; set; }
        public virtual DbSet<authOtp> authOtps { get; set; }
        public virtual DbSet<authRole> authRoles { get; set; }
        public virtual DbSet<authScreen> authScreens { get; set; }
        public virtual DbSet<authUseragent> authUseragents { get; set; }
        public virtual DbSet<flowImage> flowImages { get; set; }
        public virtual DbSet<flowPhotoshoot> flowPhotoshoots { get; set; }
        public virtual DbSet<flowPhotoshootType> flowPhotoshootTypes { get; set; }
        public virtual DbSet<flowRequest> flowRequests { get; set; }
        public virtual DbSet<flowRequestDetail> flowRequestDetails { get; set; }
        public virtual DbSet<flowRequestKey> flowRequestKeys { get; set; }
        public virtual DbSet<flowRequestState> flowRequestStates { get; set; }
        public virtual DbSet<flowReservation> flowReservations { get; set; }
        public virtual DbSet<flowReservationDetail> flowReservationDetails { get; set; }
        public virtual DbSet<flowReservationKey> flowReservationKeys { get; set; }
        public virtual DbSet<flowState> flowStates { get; set; }
        public virtual DbSet<logBrowser> logBrowsers { get; set; }
        public virtual DbSet<logCity> logCities { get; set; }
        public virtual DbSet<logCountry> logCountries { get; set; }
        public virtual DbSet<logDesktop> logDesktops { get; set; }
        public virtual DbSet<logDevice> logDevices { get; set; }
        public virtual DbSet<logEvent> logEvents { get; set; }
        public virtual DbSet<logEventDetail> logEventDetails { get; set; }
        public virtual DbSet<logEventKey> logEventKeys { get; set; }
        public virtual DbSet<logEventType> logEventTypes { get; set; }
        public virtual DbSet<logException> logExceptions { get; set; }
        public virtual DbSet<logHttp> logHttps { get; set; }
        public virtual DbSet<logInteraction> logInteractions { get; set; }
        public virtual DbSet<logInteractionDetail> logInteractionDetails { get; set; }
        public virtual DbSet<logInteractionKey> logInteractionKeys { get; set; }
        public virtual DbSet<logInteractionType> logInteractionTypes { get; set; }
        public virtual DbSet<logLocation> logLocations { get; set; }
        public virtual DbSet<logMobile> logMobiles { get; set; }
        public virtual DbSet<logModel> logModels { get; set; }
        public virtual DbSet<logO> logOS { get; set; }
        public virtual DbSet<logRegion> logRegions { get; set; }
        public virtual DbSet<logRequest> logRequests { get; set; }
        public virtual DbSet<logRequestType> logRequestTypes { get; set; }
        public virtual DbSet<logResponse> logResponses { get; set; }
        public virtual DbSet<logResponseType> logResponseTypes { get; set; }
        public virtual DbSet<logSession> logSessions { get; set; }
        public virtual DbSet<logUseragent> logUseragents { get; set; }
        public virtual DbSet<serDetail> serDetails { get; set; }
        public virtual DbSet<serKey> serKeys { get; set; }
        public virtual DbSet<serSelf> serSelves { get; set; }
        public virtual DbSet<userAddress> userAddresses { get; set; }
        public virtual DbSet<userDetail> userDetails { get; set; }
        public virtual DbSet<userKey> userKeys { get; set; }
        public virtual DbSet<userSelf> userSelves { get; set; }
        public virtual DbSet<userVehicle> userVehicles { get; set; }
        public virtual DbSet<userVehicleDetail> userVehicleDetails { get; set; }
        public virtual DbSet<vhcBrand> vhcBrands { get; set; }
        public virtual DbSet<vhcKey> vhcKeys { get; set; }
        public virtual DbSet<vhcSelf> vhcSelves { get; set; }
        public virtual DbSet<payCard> payCards { get; set; }
    }
}
