DROP PROCEDURE Vehicle_Regenerate
DROP PROCEDURE Vehicle_Generate
DROP PROCEDURE Vehicle_Fill
DROP PROCEDURE Vehicle_Create
DROP PROCEDURE Vehicle_Remove
GO

CREATE PROCEDURE Vehicle_Remove
AS

	DROP TABLE vhcKey
	DROP TABLE vhcSelf
	DROP TABLE vhcBrand

GO

CREATE PROCEDURE Vehicle_Create
AS

	CREATE TABLE vhcBrand
	(
		PK int primary key identity(0,1),
		Name varchar(50) NOT NULL,
		[Image] varchar(100) NOT NULL,
		Extras varchar(MAX) NOT NULL,
		CreateDate datetime NOT NULL,
		CreatedBy varchar(250) NOT NULL,
		UpdateDate datetime NOT NULL,
		UpdatedBy varchar(250) NOT NULL,
		RemovalDate datetime NOT NULL,
		RemovedBy varchar(250) NOT NULL,
		Present bit NOT NULL
	)	

	CREATE TABLE vhcSelf
	(
		PK int primary key identity(0,1),
		BrandFK int foreign key references vhcBrand(PK),
		Model varchar(250) NOT NULL,		
		Extras varchar(MAX) NOT NULL,
		CreateDate datetime NOT NULL,
		CreatedBy varchar(250) NOT NULL,
		UpdateDate datetime NOT NULL,
		UpdatedBy varchar(250) NOT NULL,
		RemovalDate datetime NOT NULL,
		RemovedBy varchar(250) NOT NULL,
		Present bit NOT NULL
	)	

	CREATE TABLE vhcKey
	(
		PK int primary key identity(0,1),
		Value varchar(50) NOT NULL,
		Extras varchar(MAX) NOT NULL,
		CreateDate datetime NOT NULL,
		CreatedBy varchar(250) NOT NULL,
		UpdateDate datetime NOT NULL,
		UpdatedBy varchar(250) NOT NULL,
		RemovalDate datetime NOT NULL,
		RemovedBy varchar(250) NOT NULL,
		Present bit NOT NULL
	)	

GO

CREATE PROCEDURE Vehicle_Fill
AS

	INSERT INTO vhcBrand VALUES ('NULL', 'NULL', 'NULL', GETDATE(), 'NULL', GETDATE(), 'NULL', GETDATE(), 'NULL', 0)
	INSERT INTO vhcSelf VALUES (0, 'NULL', 'NULL', GETDATE(), 'NULL', GETDATE(), 'NULL', GETDATE(), 'NULL', 0)
	INSERT INTO vhcKey VALUES ('NULL', 'NULL', GETDATE(), 'NULL', GETDATE(), 'NULL', GETDATE(), 'NULL', 0)

	INSERT INTO vhcKey VALUES ('License Plate', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcBrand VALUES ('Acura', '/acura', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Alfa Romeo', '/alfa_romeo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Anadol', '/anadol', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Aston Martin', '/aston_martin', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Audi', '/audi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Bentley', '/bentley', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('BMW', '/bmw', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Bugatti', '/bugatti', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Buick', '/buick', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Cadillac', '/cadillac', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Chery', '/chery', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Chevrolet', '/chevrolet', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Chrysler', '/chrysler', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Citroën', '/citroen', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Dacia', '/dacia', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Daewoo', '/daewoo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Daihatsu', '/daihatsu', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Dodge', '/dodge', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('DS Automobiles', '/ds', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Ferrari', '/ferrari', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Fiat', '/fiat', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Ford', '/ford', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Geely', '/geely', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Honda', '/honda', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Hyundai', '/hyundai', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Infiniti', '/infiniti', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Jaguar', '/jaguar', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Kia', '/kia', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Lada', '/lada', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Lamborghini', '/lamborghini', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Lancia', '/lancia', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Lexus', '/lexus', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Lincoln', '/lincoln', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Maserati', '/maserati', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Maybach', '/maybach', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Mazda', '/mazda', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('McLaren', '/mclaren', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Mercedes', '/mercedes', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Mini', '/mini', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Mitsubishi', '/mitsubishi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Nissan', '/nissan', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Opel', '/opel', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Pagani', '/pagani', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Peugeot', '/peugeot', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Pontiac', '/pontiac', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Porsche', '/porsche', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Proton', '/proton', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Renault', '/renault', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Rolls Royce', '/rolls_royce', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Rover', '/rover', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Saab', '/saab', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Seat', '/seat', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Skoda', '/skoda', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Smart', '/smart', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Subaru', '/subaru', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Suzuki', '/suzuki', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Tata', '/tata', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Tesla', '/tesla', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Tofaş', '/tofas', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Toyota', '/toyota', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Volkswagen', '/volkswagen', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcBrand VALUES ('Volvo', '/volvo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)



	INSERT INTO vhcSelf VALUES (1, 'RSX', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (2, '4C', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, '33', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, '75', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, '143', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, '146', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, '147', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, '155', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, '156', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, '159', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, '164', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, '166', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, 'Brera', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, 'Giulietta', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, 'GT', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, 'GTV', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, 'MiTo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (2, 'Spider', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (3, 'A', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (4, 'DB7', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (4, 'DB9', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (4, 'DB11', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (4, 'DBS', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (4, 'Rapide', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (4, 'Vanquish', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (4, 'Vantage', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (4, 'Virage', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (5, 'A1', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, 'A3', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, 'A4', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, 'A5', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, 'A6', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, 'A7', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, 'A8', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, 'R8', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, 'RS', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, 'S Serisi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, 'TT', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, '80 Serisi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, '90 Serisi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, '100 Serisi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (5, '200 Serisi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (6, 'Bentayga', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (6, 'Continental', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (6, 'Flying Spur', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (6, 'Mulsanne', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (7, '116d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '116d ED', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '116i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '118d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '118i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '120d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '120i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '135i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '216d Active Tourer', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '216d Active Tourer', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '216d Gran Tourer', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '218i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '218i Active Tourer', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '220d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '315', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '315', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '316', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '316Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '316i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '316ti', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '318Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '318d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '318i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '318is', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '318tds', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '318ti', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '320Cd', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '320Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '320d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '320d GT', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '320d xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '320d xDrive GT', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '320i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '320i ED', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '320si', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '320td', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '323Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '323i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '324d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '324td', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '325Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '325i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '325td', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '325tds', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '325ti', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '325xi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '328Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '328i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '330Cd', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '330Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '330d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '330i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '330i xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '330xd', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '330xi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '335i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '418d Gran Coupe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '418d Gran Coupe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '418i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '418i Gran Coupe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '420d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '420d Gran Coupe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '420d xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '420d xDrive Gran Coupe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '428i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '428i xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '428i xDrive Gran Coupe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '430i xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '430i xDrive Gran Coupe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '518i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '518i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '520', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '520d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '520d Gran Turismo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '520d xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '520i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '520Li', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '523i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '524td', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '525d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '525d xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '525i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '525tds', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '525 xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '525xi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '528i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '528i xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '530d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '530i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '530i xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '530xd Gran Turismo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '530 xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '530xi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '535d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '535d xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '535i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '535i xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '540i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '543i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '550d xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '550 xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '630Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '630Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '630i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '630i Gran Turismo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '635CSi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '635d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '640d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '640d xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '640i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '640xd', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '643Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '650Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '650i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '650i xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '725d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '725d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '725d Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '725tds', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '728i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '728i Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '730d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '730d Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '730d xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '730d xDrive Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '730i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '730i Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '735i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '735i Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '740d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '740d xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '740d xDrive Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '740e xDrive Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '740i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '740i Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '743d', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '743i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '743i Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '750d xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '750d xDrive Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '750i', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '750i Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '750i xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '750i xDrive Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '760i Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '760i xDrive Long', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '840Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '840Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, '850Ci', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'i3', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'i3', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'i8', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'M1', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'M1', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'M2', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'M240i xDrive', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'M3', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'M3 Cabrio', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'M3 Coupe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'M4', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'M4 Competition', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'M5', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'M6', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'M6 Cabrio', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'M6 Gran Coupe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'Z4 M', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'Z3', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'Z3', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (7, 'Z4', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (8, 'Chiron', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (8, 'Veyron', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (9, 'Century', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (9, 'Park Avenue', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (9, 'Regal', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (9, 'Roadmaster', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (10, 'BLS', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (10, 'Brougham', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (10, 'CTS', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (10, 'DeVille', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (10, 'Eldorado', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (10, 'Fleetwood', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (10, 'Seville', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (10, 'STS', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (11, 'Alia', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (11, 'Chance', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (11, 'Kimo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (11, 'Niche', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (12, 'Aveo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Camaro', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Caprice', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Cavalier', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Celebrity', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Corvette', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Cruze', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Epica', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Evanda', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Geo Storm', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Impala', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Kalos', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Lacetti', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Lumina', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Rezzo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (12, 'Spark', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (13, '300 C', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (13, '300 M', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (13, 'Concorde', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (13, 'Crossfire', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (13, 'Le Baron', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (13, 'LHS', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (13, 'Neon', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (13, 'PT Cruiser', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (13, 'Sebring', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (13, 'Stratus', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (14, 'AX', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'BX', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'C-Elysée', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'C1', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'C2', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'C3', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'C3 Picasso', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'C4', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'C4 Picasso', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'C4 Grand Picasso', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'C5', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'C6', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'C8', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'Evasion', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'Saxo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'Xantia', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'XM', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'Xsara', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (14, 'ZX', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (15, '1310', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (15, 'Lodgy', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (15, 'Logan', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (15, 'Nova', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (15, 'Sandero', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (15, 'Solenza', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (16, 'Chairman', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (16, 'Espero', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (16, 'Lanos', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (16, 'Leganza', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (16, 'Matiz', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (16, 'Nexia', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (16, 'Nubira', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (16, 'Racer', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (16, 'Tico', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (17, 'Applause', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (17, 'Charade', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (17, 'Copen', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (17, 'Cuore', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (17, 'Materia', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (17, 'Sirion', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (17, 'YRV', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (18, 'Avenger', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (18, 'Challenger', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (18, 'Charger', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (18, 'Diplomat', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (18, 'Viper', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (19, 'DS 3', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (19, 'DS 4', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (19, 'DS 4 Crossback', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (19, 'DS 5', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (20, '360', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (20, '430', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (20, '436', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (20, '488', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (20, '438', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (20, '512', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (20, '575', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (20, '599', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (20, '612', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (20, 'California', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (20, 'F355', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (20, 'FF', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (20, 'F Serisi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (20, 'GTC4Lusso', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (21, '124 Spider', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, '126 Bis', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, '500 Ailesi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Albea', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Brava', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Bravo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Coupe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Croma', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Egea', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Idea', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Linea', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Marea', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Mirafiori', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Palio', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Panda', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Punto', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Sedici', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Siena', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Stilo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Tempra', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Tipo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Ulysse', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (21, 'Uno', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (22, 'B-Max', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'C-Max', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Cougar', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Crown Victoria', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Escort', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Festiva', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Fiesta', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Focus', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Fusion', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Galaxy', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Granada', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Grand C-Max', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Ka', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Mondeo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Mustang', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Probe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Scorpio', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Sierra', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'S-Max', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Taunus', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (22, 'Taurus', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (23, 'Echo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (23, 'Emgrand', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (23, 'Familia', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (23, 'FC', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (24, 'Accord', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (24, 'City', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (24, 'Civic', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (24, 'CRX', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (24, 'CR-Z', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (24, 'Integra', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (24, 'Jazz', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (24, 'Legend', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (24, 'Prelude', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (24, 'S2000', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (24, 'Shuttle', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (24, 'Stream', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (25, 'Accent', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'Accent Blue', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'Accent Era', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'Atos', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'Coupe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'Elantra', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'Excel', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'Genesis', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'Getz', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'Grandeur', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'Ioniq', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'i10', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'i20', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'i20 Active', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'i20 Troy', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'i30', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'i40', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'iX20', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'Matrix', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'S-Coupe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'Sonata', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (25, 'Trajet', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (26, 'G', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (26, 'I30', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (26, 'M', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (26, 'Q30', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (26, 'Q50', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (26, 'Q60', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (27, 'Daimler', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (27, 'F-Type', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (27, 'Sovereign', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (27, 'S-Type', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (27, 'XE', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (27, 'XF', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (27, 'XJ', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (27, 'XJR', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (27, 'XJS', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (27, 'XK8', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (27, 'XKR', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (27, 'X-Type', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (28, 'Capital', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Carens', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Ceed', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Cerato', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Clarus', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Magentis', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Opirus', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Optima', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Picanto', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Pride', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Pro Ceed', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Rio', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Sephia', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Shuma', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Sorento', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Soul', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (28, 'Venga', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (29, 'Kalina', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (29, 'Samara', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (29, 'VAZ', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (29, 'Vega', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (30, 'Aventador', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (30, 'Gallardo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (30, 'Huracan', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (31, 'Delta', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (31, 'Thema', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (31, 'Y (Ypsilon)', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (31, 'Zeta', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (32, 'IS', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (32, 'LS', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (32, 'RC', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (33, 'Continental', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (33, 'LS', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (33, 'Mark', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (33, 'MKS', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (33, 'Town Car', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (34, '4 Serisi', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (34, 'Cambiocorsa', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (34, 'Ghiuseri', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (34, 'GranCabrio', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (34, 'GranSport', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (34, 'GranTurismo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (34, 'GT', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (34, 'Quattroporte', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (34, 'Spyder', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (35, '62', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (36, '2', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (36, '3', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (36, '5', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (36, '6', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (36, 'MPV', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (36, '121', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (36, '323', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (36, '626', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (36, '929', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (36, 'Lantis', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (36, 'MX', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (36, 'Premacy', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (36, 'RX', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (36, 'Xedos', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (37, '675LT Spider', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (37, '720S', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (38, 'A', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'AMG GT', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'B', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'C', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'CL', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'CLA', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'CLC', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'CLK', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'CLS', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'E', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'Maybach S', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'R', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'S', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'SL', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'SLC', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'SLK', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, 'SLS AMG', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '190', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '200', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '220', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '230', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '240', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '250', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '260', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '280', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '300', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '320', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '380', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '420', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '500', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '560', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (38, '600', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (39, 'Cooper', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (39, 'Cooper Clubman', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (39, 'Cooper S', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (39, 'John Cooper', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (39, 'One', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (40, 'Attrage', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (40, 'Carisma', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (40, 'Colt', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (40, 'Eclipse', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (40, 'Galant', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (40, 'Lancer', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (40, 'Lancer Evolution', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (40, 'Space Star', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (40, 'Space Wagon', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (41, '200 SX', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, '300 ZX', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, '350 Z', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, 'Almera', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, 'Altima', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, 'Bluebird', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, 'GT-R', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, 'Laurel Altima', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, 'Maxima', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, 'Micra', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, 'Note', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, 'NX Coupe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, 'Primera', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, 'Pulsar', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (41, 'Sunny', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (42, 'Adam', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Agila', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Ampera', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Ascona', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Astra', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Calibra', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Cascada', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Corsa', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'GT (Roadster)', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Insignia', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Kadett', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Manta', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Meriva', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Omega', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Rekord', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Senator', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Signum', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Tigra', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Vectra', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (42, 'Zafira', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (43, 'Huayra', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (43, 'Zonda', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (44, '106', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '107', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '205', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '206', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '206 +', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '207', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '208', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '301', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '305', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '306', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '307', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '308', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '309', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '405', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '406', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '407', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '508', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '605', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '607', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '806', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, '807', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (44, 'RCZ', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (45, 'Firebird', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (45, 'Grand Am', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (45, 'Solstice', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (45, 'Sunbird', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
							 
	INSERT INTO vhcSelf VALUES (46, '718', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (46, '911', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (46, '928', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (46, 'Boxster', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (46, 'Cayman', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (46, 'Panamera', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (47, '218', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (47, '315', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (47, '415', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (47, '416', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (47, '418', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (47, '420', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (47, 'Gen-2', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (47, 'Persona', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (47, 'Savvy', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (47, 'Waja', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (48, 'Clio', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Espace', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Fluence', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Fluence Z.E.', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Laguna', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Latitude', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Megane', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Modus', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Safrane', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Symbol', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Twizy', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'ZOE', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Scenic', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Grand Scenic', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Talisman', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Twingo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'Vel Satis', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'R 5', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'R 9', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'R 11', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'R 12', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'R 19', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'R 21', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (48, 'R 25', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (49, 'Ghost', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (49, 'Park Ward', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (49, 'Phantom', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (49, 'Wraith', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (50, '25', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '43', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '75', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '111', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '200', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '214', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '216', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '220', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '400', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '414', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '416', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '420', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '620', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '623', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '820', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, '827', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (50, 'Streetwise', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (51, '900', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (51, '9000', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (51, '9-3', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (51, '9-5', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (52, 'Alhambra', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (52, 'Altea', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (52, 'Arosa', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (52, 'Cordoba', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (52, 'Exeo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (52, 'Ibiza', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (52, 'Leon', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (52, 'Marbella', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (52, 'Toledo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (53, 'Citigo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (53, 'Fabia', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (53, 'Favorit', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (53, 'Felicia', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (53, 'Forman', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (53, 'Octavia', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (53, 'Rapid', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (53, 'Roomster', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (53, 'Superb', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (54, 'Forfour', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (54, 'Fortwo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (54, 'Roadster', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (55, 'BRZ', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (55, 'Impreza', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (55, 'Justy', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (55, 'Legacy', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (55, 'Leone', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (55, 'Levorg', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (55, 'Vivio', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (56, 'Alto', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (56, 'Baleno', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (56, 'Liana', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (56, 'Maruti', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (56, 'S-Cross', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (56, 'Splash', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (56, 'Swift', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (56, 'SX4', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (56, 'Wagon R', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (57, 'Indica', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (57, 'Indigo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (57, 'Manza', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (57, 'Marina', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (57, 'Vista', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (58, 'Model S', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (58, 'Model X', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (59, 'Doğan', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (59, 'Kartal', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (59, 'Murat', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (59, 'Serçe', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (59, 'Şahin', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (60, 'Auris', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Avensis', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Aygo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Camry', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Carina', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Celica', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Corolla', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Corona', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Cressida', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'GT 86', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'MR2', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Prius', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Starlet', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Supra', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Urban Cruiser', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Verso', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (60, 'Yaris', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (61, 'Arteon', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'Bora', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'EOS', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'Golf', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'Jetta', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'Lupo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'New Beetle', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'The Beetle', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'Passat', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'Passat Variant', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'Phaeton', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'Polo', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'Santana', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'Scirocco', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'Sharan', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'Touran', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'Vento', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (61, 'VW CC', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)

	INSERT INTO vhcSelf VALUES (62, 'C30', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, 'C70', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, 'S40', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, 'S60', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, 'S70', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, 'S80', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, 'S90', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, 'V40', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, 'V40 Cross Country', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, 'V50', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, 'V60', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, 'V70', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, 'V90 Cross Country', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, '240', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, '243', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, '440', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, '460', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, '740', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, '850', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, '940', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)
	INSERT INTO vhcSelf VALUES (62, '960', '', GETDATE(), 'DB', GETDATE(), '', GETDATE(), '', 1)	

GO

CREATE PROCEDURE Vehicle_Generate
AS
	
	EXEC Vehicle_Create
	EXEC Vehicle_Fill

GO

CREATE PROCEDURE Vehicle_Regenerate
AS
	
	EXEC Vehicle_Remove
	EXEC Vehicle_Generate

GO
